### ISSUE TITLE
Does it have any compression of the images?

### ISSUE THREAD

**Issue by iambeingtracked** [ZizzyDizzyMC/linx-server#26]
That's more of a question that i'd really like to ask. If it does, is it possible to disable?

**Comment by BBaoVanC** [comment]
As far as I can tell there's no compression

**Comment by ZizzyDizzyMC** [comment]
Hello, by default Linx does not have compression of images.  As it's a file host, I generally wouldn't recommend compressing images as they lose quality that way.

**Comment by ZizzyDizzyMC** [comment]
Closing issue as a file host, compression is up to the uploader.
